# Generated by Django 4.2.3 on 2023-07-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_mainpagearticle"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainPageArticle",
        ),
        migrations.AddField(
            model_name="post",
            name="on_mainpage",
            field=models.BooleanField(default=False, verbose_name="on mainpage"),
        ),
    ]
