# Generated by Django 4.2.3 on 2023-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_delete_mainpagearticle_post_on_mainpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="on_mainpage",
        ),
        migrations.AddField(
            model_name="post",
            name="post_class",
            field=models.IntegerField(
                choices=[(0, "regular post"), (1, "mainpage post"), (2, "cv post")],
                default=0,
            ),
        ),
    ]
